### ISSUE TITLE
Test topological sort

### ISSUE THREAD

**Issue by pradkrish** [fhamonic/melon#2]
I see that topological sort got no tests. Perhaps that could be my good first contribution. Can you assign this issue to me?

**Comment by pradkrish** [comment]
Topological sort in the current form will always fail at `assert(!finished)` in both functions `current()` and `advance()` regardless of the graph structure. One way is to avoid this could be push the first vertex into the queue in the constructor. What are your thoughts? I am happy to implement the fix along with the tests.

**Comment by fhamonic** [comment]
You are right, I think that the missing part is calling the method reset() in the constructor. Thanks for finding this, I'll let you fix it :)

**Comment by pradkrish** [comment]
Thanks.  A question, let's say if I build a graph with only 2 nodes and create an arc between node0 and node1 in the following way

```python
static_digraph_builder<static_digraph> builder(2);
builder.add_arc(0,1);
```
I was expecting  `add_arc(u,v)` where `u` is source vertex and `v` is target vertex and hence `in_degree(_graph.get(), node0)` to give `0` and `in_degree(_graph.get(), node1)` to give `1`. But the `in_degree(..)` function returns `0` for node1 and `1` for node0, Is that expected?
